[2024-11-14T17:11:26.722+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T17:11:26.756+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T17:11:25.514638+00:00 [queued]>
[2024-11-14T17:11:26.765+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T17:11:25.514638+00:00 [queued]>
[2024-11-14T17:11:26.768+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T17:11:26.779+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 17:11:25.514638+00:00
[2024-11-14T17:11:26.785+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_DAG_ELT_dbt', 'dbt_run', 'manual__2024-11-14T17:11:25.514638+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/Stock_DAG_ELT.py', '--cfg-path', '/tmp/tmp4xp86zwj']
[2024-11-14T17:11:26.788+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask dbt_run
[2024-11-14T17:11:26.791+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=772) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T17:11:26.792+0000] {standard_task_runner.py:63} INFO - Started process 773 to run task
[2024-11-14T17:11:26.825+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T17:11:25.514638+00:00 [running]> on host 214073c88124
[2024-11-14T17:11:26.897+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_DAG_ELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T17:11:25.514638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T17:11:25.514638+00:00'
[2024-11-14T17:11:26.898+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T17:11:26.917+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T17:11:26.918+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-14T17:11:26.926+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T17:11:26.931+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-11-14T17:11:26.931+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-14T17:11:26.932+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T17:11:26.940+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-14T17:11:26.945+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stock_DAG_ELT_dbt, task_id=dbt_run, run_id=manual__2024-11-14T17:11:25.514638+00:00, execution_date=20241114T171125, start_date=20241114T171126, end_date=20241114T171126
[2024-11-14T17:11:26.955+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 773)
[2024-11-14T17:11:26.966+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T17:11:26.982+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T17:11:26.987+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
