[2024-11-14T18:33:17.471+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T18:33:17.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T18:33:16.015036+00:00 [queued]>
[2024-11-14T18:33:17.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T18:33:16.015036+00:00 [queued]>
[2024-11-14T18:33:17.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T18:33:17.541+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 18:33:16.015036+00:00
[2024-11-14T18:33:17.547+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_DAG_ELT_dbt', 'dbt_run', 'manual__2024-11-14T18:33:16.015036+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/Stock_DAG_ELT.py', '--cfg-path', '/tmp/tmpbyn9bwj2']
[2024-11-14T18:33:17.550+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask dbt_run
[2024-11-14T18:33:17.551+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3517) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T18:33:17.552+0000] {standard_task_runner.py:63} INFO - Started process 3518 to run task
[2024-11-14T18:33:17.585+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T18:33:16.015036+00:00 [running]> on host 214073c88124
[2024-11-14T18:33:17.659+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_DAG_ELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T18:33:16.015036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T18:33:16.015036+00:00'
[2024-11-14T18:33:17.660+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T18:33:17.682+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T18:33:17.683+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-14T18:33:17.690+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T18:33:19.528+0000] {subprocess.py:93} INFO - [0m18:33:19  Running with dbt=1.8.7
[2024-11-14T18:33:21.128+0000] {subprocess.py:93} INFO - [0m18:33:21  Registered adapter: snowflake=1.8.4
[2024-11-14T18:33:21.205+0000] {subprocess.py:93} INFO - [0m18:33:21  Encountered an error:
[2024-11-14T18:33:21.205+0000] {subprocess.py:93} INFO - Compilation Error
[2024-11-14T18:33:21.206+0000] {subprocess.py:93} INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-11-14T18:33:22.037+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-14T18:33:22.038+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T18:33:22.047+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-14T18:33:22.053+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stock_DAG_ELT_dbt, task_id=dbt_run, run_id=manual__2024-11-14T18:33:16.015036+00:00, execution_date=20241114T183316, start_date=20241114T183317, end_date=20241114T183322
[2024-11-14T18:33:22.064+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 3518)
[2024-11-14T18:33:22.101+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T18:33:22.120+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T18:33:22.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
